### ISSUE TITLE
TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by ShavonnahTiera** [meteor/tutorial-tools#11]
I get this error when I updated the package.js file:

`Exception from Tracker recompute function:
TypeError: Cannot read property 'files' of undefined
    at .<anonymous> (diff-box.jsx:36)`

I left out a, then added in a .md step in the api array and regenerated the script. When I added everything in and ran my viewer, I got this lovely bit of sadness.

**Comment by kamilkisiela** [comment]
@ShavonnahTiera Maybe the step you want to use DiffBox on is missing?
