### ISSUE TITLE
Git patch file parser have some issues with multiple change for same file

### ISSUE THREAD

**Issue by dotansimha** [meteor/tutorial-tools#3]
Hi,

Try to create a diff patch file and use it. 
For files with one or more changes in the same "area" of the file the parser works great.
But if I have two changes for the file, and one of them is in the begining and the other is in the end of the file, and the file is NOT small - The diff box shows unwanted results.

Example:
<img width="866" alt="screen shot 2015-08-18 at 20 26 48" src="https://cloud.githubusercontent.com/assets/3680083/9337342/7cfba3de-45e7-11e5-9d3c-802b42aff421.png">

Any idea?

Thanks

**Comment by stubailo** [comment]
Finished first part of fix - the parser will now return an array of sections in the case where the patch has multiple parts. Now to update the viewer accordingly.

https://github.com/meteor/git-patch-parser/commit/fc23ef6e14060f9b9d693d96d45ecdac907b0996

**Comment by stubailo** [comment]
OK, now updated the patch viewer component to work with it. Let me know what you think - we can fiddle with the wording/styling a bit.

If you update the package it should just work automatically.

**Comment by dotansimha** [comment]
Works great! Thanks !!
