### ISSUE TITLE
"No newline at end of file" printed for most of my diffs

### ISSUE THREAD

**Issue by dotansimha** [meteor/tutorial-tools#4]
You can see at the bottom of the diffbox.

Is there a way to hide this?

<img width="866" alt="screen shot 2015-08-18 at 20 26 48" src="https://cloud.githubusercontent.com/assets/3680083/9337708/a0c9956c-45e9-11e5-8a94-fa8d5c1d74d5.png">

Thanks

**Comment by stubailo** [comment]
Github also complains about this, but more subtly: https://www.dropbox.com/s/wt1kmdkx13fdy3r/Screenshot%202015-08-18%2017.26.35.png?dl=0

http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

However, this is probably something that I should just get rid of automatically.

**Comment by stubailo** [comment]
@dotansimha can you send me your patch file so that I can use it as a test case?

**Comment by dotansimha** [comment]
@stubailo 
Sure.

You can find it here:
https://github.com/Urigo/angular-meteor/blob/master/.docs/angular-meteor/client/content/patches/angular-meteor.multi.patch

You can see that the original patch file has these, so I think that just regular replace will fix it..

**Comment by dotansimha** [comment]
@stubailo 
Hi, fixed it in the parser 
https://github.com/meteor/git-patch-parser/pull/3

**Comment by dotansimha** [comment]
Looks like that: 
<img width="822" alt="screen shot 2015-08-19 at 23 29 05" src="https://cloud.githubusercontent.com/assets/3680083/9368108/1fafd130-46ca-11e5-8ab9-0a464f907249.png">

Is that okay? 

And I will add a test

**Comment by stubailo** [comment]
I suspect the big gap at the bottom is the blank line I was talking about.
