### ISSUE TITLE
ENOENT on tutorial build

### ISSUE THREAD

**Issue by Tallyb** [meteor/tutorial-tools#7]
When running meteor / meteor update I get ENOENT on both of those packages:

mdg:tutorial-diff-box 
mdg:tutorial-step-diff-compiler

Error: ENOENT, mkdir 'D:\dev\angular-meteor.docs\angular-meteor\packages\tutorial-step-diff-compiler.npm\plugin\mdg:tutorial-step-diffs-plugin-new-8fezek'

On windows 10.

**Comment by stubailo** [comment]
What version of Meteor are you running?

**Comment by Tallyb** [comment]
1.1.0.3

**Comment by stubailo** [comment]
Never did anything about this, hope that's OK.
