### ISSUE TITLE
DiffBox issue with special HTML symbols

### ISSUE THREAD

**Issue by barbatus** [meteor/tutorial-tools#8]
DiffBox has troubles to show correctly special HTML symbols in non HTML files.
For example, if a Git patch file contains a generic type expression (used in a TypeScript file):

``` ts
let array = new Array<Object>();
```

It eventually will be shown as 

``` ts
let array = new Array();
```

where `<Object>` is omitted.

Workaround is to escape `<` symbol with the `&lt;` sequence.

Is any way to fix it?

**Comment by stubailo** [comment]
Yeah I think you'd want to patch this file: https://github.com/meteor/tutorial-tools/blob/0053610cdeccadc09b3e722ce4b93d35756ce419/tutorial-diff-box/diff-box.jsx#L76

Basically, you need to do the HTML escape before you call the highlighting code.

**Comment by Urigo** [comment]
fixed with the latest release
